name: "Alteza GH Action"
description: "A composite action that builds and deploys an Alteza website"
author: "Arjun Menon"

inputs:
  path:
    description: "Path of the directory containing the input Alteza content."
    required: true
    default: "test_content"

outputs:
  page_url:
    description: 'URL to deployed GitHub Pages'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install alteza

    - name: Generate
      shell: bash
      run: |
        echo Generating with Alteza...
        echo PWD: `pwd`
        alteza --content test_content --output alteza-output

    - name: Display structure of files
      shell: bash
      run: ls -laR --ignore=.git

    - name: Upload website ZIP file
      uses: actions/upload-artifact@v3
      with:
        name: alteza-output
        path: alteza-output

    - name: Configure GitHub Pages
      id: gh_pages_config
      uses: actions/configure-pages@v3
      with:
        enablement: true

    - name: Display output of the GitHub Pages configuration step
      env:
        GH_PAGES_BASE_URL: ${{ steps.gh_pages_config.outputs.base_url }}
        GH_PAGES_BASE_ORIGIN: ${{ steps.gh_pages_config.outputs.origin }}
        GH_PAGES_BASE_HOST: ${{ steps.gh_pages_config.outputs.host }}
        GH_PAGES_BASE_PATH: ${{ steps.gh_pages_config.outputs.base_path }}
      shell: bash
      run: |
        echo "GitHub Pages site full base URL: $GH_PAGES_BASE_URL"
        echo "GitHub Pages site origin: $GH_PAGES_BASE_ORIGIN"
        echo "GitHub Pages site origin: $GH_PAGES_BASE_HOST"
        echo "GitHub Pages site full base path: $GH_PAGES_BASE_PATH"

    - name: Upload artifact to GitHub Pages
      uses: actions/upload-pages-artifact@v2
      with:
        path: alteza-output

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2

    - name: Display deployed GitHub Pages URL
      env:
        GH_PAGE_URL: ${{ steps.deployment.outputs.page_url }}
      shell: bash
      run: |
        echo "GitHub Pages URL: $GH_PAGE_URL"
        echo "::set-output name=page_url::$GH_PAGE_URL"

