name: Pylint

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  #
  # Skip if source hasn't changed.
  #
  should_skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          skip_after_successful_duplicate: 'true'
          paths: '["alteza/**", "**/pylint.yml"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  pylint:
    needs: should_skip
    if: needs.should_skip.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    strategy:
      matrix:
        python-version: [ "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Analysing the code with pylint
        run: |
          pylint -j 0 alteza

      - name: Run pyreverse
        run: |
          mkdir class-structure
          pyreverse --output html --output-directory class-structure alteza

      - name: Upload class structure diagrams
        if: matrix.python-version == '3.10'
        uses: actions/upload-artifact@v3
        with:
          name: class-structure
          path: class-structure

