name: Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: '3.11'
#          cache: pip
#          cache-dependency-path: setup.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install alteza

      - name: Generate
        run: |
          alteza -h

