name: Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install alteza

      - name: Generate
        run: |
          echo Generating with Alteza...
          echo PWD: `pwd`
          alteza --content test_content --output alteza-output

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: alteza-output
          path: alteza-output

  publish:
    needs:
      - generate
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Display PWD
        run: |
          echo PWD: `pwd`

      - name: Display structure of files before download
        run: ls -R

      - uses: actions/download-artifact@v3
        with:
          name: alteza-output

      - name: Display structure of downloaded files
        run: ls -R

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Display structure afterward
        run: ls -R
