name: Test

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install alteza

      - name: Generate
        run: |
          echo PWD: `pwd`
          alteza -content test_content --output alteza-output

