name: Type Checks

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  #
  # Skip type checks if source hasn't changed.
  #
  should_skip:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          skip_after_successful_duplicate: 'true'
          paths: '["alteza/**"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  #
  # Pyre Check
  #
  pyre:
    needs: should_skip
    # if: needs.should_skip.outputs.should_skip != 'true'
    if: 'false'
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run Pyre
        uses: facebook/pyre-action@v0.0.2
        with:
          # To customize these inputs:
          # See https://github.com/facebook/pyre-action#inputs
          repo-directory: './'
          requirements-path: 'requirements.txt'
          version: '0.9.19'

  #
  # Mypy Check
  #
  mypy:
    needs: should_skip
    if: needs.should_skip.outputs.should_skip != 'true'
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Mypy Check
        run: |
          mypy alteza

  #
  # Pyright Check
  #
  pyright:
    needs: should_skip
    if: needs.should_skip.outputs.should_skip != 'true'
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Pyright Check
        run: |
          pyright alteza

  #
  # Pytype Check
  #
  pytype:
    needs: should_skip
    if: needs.should_skip.outputs.should_skip != 'true'
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Pytype Check
        run: |
          pytype alteza

  #
  # Pyflakes Check
  #
  pyflakes:
    needs: should_skip
    if: needs.should_skip.outputs.should_skip != 'true'
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Pytype Check
        run: |
          pyflakes alteza
